ARG java_version
FROM bearstech/java-dev:${java_version}

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -eux \
    &&  export http_proxy=${HTTP_PROXY} \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends wget unzip \
    &&  rm -rf /var/lib/apt/lists/*

ENV GRADLE_VERSION=5.4.1
ENV GRADLE_HOME /opt/gradle

RUN wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip \
    && wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip.sha256 \
    && echo "$(cat gradle-${GRADLE_VERSION}-bin.zip.sha256)  gradle-${GRADLE_VERSION}-bin.zip" | sha256sum --check \
    && unzip gradle-${GRADLE_VERSION}-bin.zip \
    && rm gradle-${GRADLE_VERSION}-bin.zip gradle-${GRADLE_VERSION}-bin.zip.sha256 \
    && mv gradle-${GRADLE_VERSION} ${GRADLE_HOME} \
    && ln -s /opt/gradle/bin/gradle /usr/local/bin/gradle

# generated labels

ARG GIT_VERSION
ARG GIT_DATE
ARG BUILD_DATE

LABEL \
    com.bearstech.image.revision_date=${GIT_DATE} \
    org.opencontainers.image.authors=Bearstech \
    org.opencontainers.image.revision=${GIT_VERSION} \
    org.opencontainers.image.created=${BUILD_DATE} \
    org.opencontainers.image.url=https://github.com/factorysh/docker-java \
    org.opencontainers.image.source=https://github.com/factorysh/docker-java/blob/${GIT_VERSION}/Dockerfile.gradle
