FROM bearstech/debian:stretch

ENV DEBIAN_FRONTEND noninteractive

ARG jdkjre=jre
RUN echo "deb http://deb.debian.org/debian stretch-backports main" > /etc/apt/sources.list.d/backport.list \
    && apt-get update \
    && apt-get -t stretch-backports install  -y --no-install-recommends \
            openjdk-11-${jdkjre}-headless \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

ARG GIT_VERSION
LABEL com.bearstech.source.java=https://github.com/factorysh/docker-java/commit/${GIT_VERSION}
