FROM bearstech/debian:stretch

ENV DEBIAN_FRONTEND noninteractive

RUN echo "deb http://deb.debian.org/debian stretch-backports main" > /etc/apt/sources.list.d/backport.list \
    && apt-get update \
    && apt-get -t stretch-backports install  -y --no-install-recommends \
            openjdk-11-jdk-headless \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/*

ARG GIT_VERSION
LABEL com.bearstech.source.java=https://github.com/factorysh/docker-java/commit/${GIT_VERSION}
