ARG java_version
FROM bearstech/java:${java_version}

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update \
    && apt-get install -y --no-install-recommends unzip \
    && rm -rf /var/lib/apt/lists/*

ENV GRADLE_VERSION=5.4.1
ENV GRADLE_HOME /opt/gradle

RUN wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip \
    && wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip.sha256 \
    && echo "$(cat gradle-${GRADLE_VERSION}-bin.zip.sha256)  gradle-${GRADLE_VERSION}-bin.zip" | sha256sum --check \
    && unzip gradle-${GRADLE_VERSION}-bin.zip \
    && rm gradle-${GRADLE_VERSION}-bin.zip gradle-${GRADLE_VERSION}-bin.zip.sha256 \
    && mv gradle-${GRADLE_VERSION} ${GRADLE_HOME} \
    && ln -s /opt/gradle/bin/gradle /usr/local/bin/gradle
